"""Data loading and validation module."""

import json
import os
from typing import Optional, Dict
from config import DEFAULT_COUNTRY_CODE, DEFAULT_STATE_CODE, DEFAULT_ISD_CODE, DEFAULT_ISD_LABEL


class DataLoadError(Exception):
    """Raised when application data cannot be loaded or parsed."""
    pass


class DataHandler:
    """Handles loading and validation of application data from JSON."""
    
    @staticmethod
    def load_from_json(json_file: str = "data.json") -> Optional[Dict]:
        """Load application data from JSON file.

        Inputs are assumed to be pre-validated, so no per-field requirement
        checks are performed here. Only structural problems (missing file,
        malformed JSON, unreadable file) raise a DataLoadError.
        """
        if not os.path.exists(json_file):
            print(f"[ERROR] JSON file not found: {json_file}")
            DataHandler._create_sample_json(json_file)
            return None
        
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            raise DataLoadError(f"Invalid JSON format in {json_file}: {e}") from e
        except OSError as e:
            raise DataLoadError(f"Could not read {json_file}: {e}") from e

        if not isinstance(data, dict):
            raise DataLoadError(f"{json_file} must contain a JSON object, got {type(data).__name__}")

        # Add internal fields
        data["country_code"] = DEFAULT_COUNTRY_CODE
        data["state_code"] = DEFAULT_STATE_CODE
        data["isd_code"] = DEFAULT_ISD_CODE
        data["isd_label"] = DEFAULT_ISD_LABEL

        print(f"[+] Loaded data from {json_file}")
        return data
    
    @staticmethod
    def _create_sample_json(json_file: str) -> None:
        """Create an empty schema JSON file when INPUT.json is missing."""
        print("[*] INPUT.json not found — this should be generated by finalize-application endpoint.")
        print("[*] Creating empty schema template...")
        
        sample_data = {
            "first_name": "",
            "last_name": "",
            "middle_name": "",
            "dob": "",
            "email": "",
            "phone": "",
            "aadhaar_first_8": "",
            "aadhaar_last_4": "",
            "name_on_aadhaar": "",
            "gender": "",
            "father_first_name": "",
            "father_last_name": "",
            "mother_first_name": "",
            "mother_middle_name": "",
            "mother_last_name": "",
            "residential_status": "Resident",
            "flat_room_door": "",
            "building_village": "",
            "road_street_post": "",
            "area_locality": "",
            "country": "INDIA",
            "state": "",
            "pin_code": "",
            "verifier_place": "",
            "verifier_designation": "",
            "delivery_option": "physical",
            "photo_file": "docs/jphoto.jpeg",
            "signature_file": "docs/jsign.jpeg",
            "aadhaar_pdf": "docs/jaadhar.pdf",
            "birth_cert_pdf": "docs/jbirthcert.pdf"
        }
        
        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(sample_data, f, indent=4, ensure_ascii=False)
        
        print(f"[*] Created empty template at {json_file}")
        print(f"[*] Run finalize-application endpoint to populate this file with real data.")
    
    @staticmethod
    def save_payment_info(payment_url: str, screenshot_path: str, data: Dict) -> None:
        """Save payment information to JSON file."""
        import datetime
        
        payment_data = {
            "payment_url": payment_url,
            "screenshot": screenshot_path,
            "timestamp": datetime.datetime.now().isoformat(),
            "applicant_name": f"{data.get('first_name', '')} {data.get('last_name', '')}".strip(),
            "email": data.get('email', '')
        }
        
        with open("payment_link.json", 'w', encoding='utf-8') as f:
            json.dump(payment_data, f, indent=4, ensure_ascii=False)
        
        print("[+] Payment link saved to: payment_link.json")
